# Generated by Django 4.0.5 on 2022-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pass_change_force',
            field=models.BooleanField(default=True),
        ),
    ]
