# Generated by Django 4.0.5 on 2022-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
