# Generated by Django 4.0.5 on 2022-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, unique=True),
        ),
    ]
