# Generated by Django 4.0.5 on 2022-06-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0003_alter_obligation_optional_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation', to='split_app.transaction'),
        ),
    ]
