# Generated by Django 4.0.5 on 2022-06-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0004_alter_obligation_desc_alter_obligation_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
