# Generated by Django 4.0.5 on 2022-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("split_app", "0005_alter_transaction_t_date_alter_transaction_t_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="t_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="t_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
