# Generated by Django 4.0.5 on 2022-07-04 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split_app', '0006_alter_transaction_t_date_alter_transaction_t_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
