# Generated by Django 4.0.5 on 2022-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0008_alter_transaction_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
